# Generated by Django 5.0.4 on 2024-05-15 15:49

import ArticoApp.products.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('Paintings', 'Paintings'), ('Sculptures', 'Sculptures'), ('Photography', 'Photography'), ('Jewelry', 'Jewelry'), ('Toys', 'Toys'), ('Digital Art', 'Digital Art'), ('Other', 'Other')], default='Other', max_length=50)),
                ('copies', models.IntegerField(default=1)),
                ('short_description', models.TextField()),
                ('long_description', models.TextField()),
                ('product_photo', models.ImageField(upload_to='product_photo/', validators=[ArticoApp.products.models.MaxFileSizeValidator(limit_value=5242880)])),
                ('slug', models.SlugField(blank=True, editable=False, max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
