# Generated by Django 5.0.4 on 2024-04-14 17:29

import ArticoApp.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_created_at_product_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_photo',
            field=models.ImageField(blank=True, upload_to='product_photo/', validators=[ArticoApp.products.models.MaxFileSizeValidator(limit_value=5242880)]),
        ),
    ]
