# Generated by Django 5.0.4 on 2024-04-18 21:15

import ArticoApp.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_photo',
            field=models.ImageField(upload_to='product_photo/', validators=[ArticoApp.products.models.MaxFileSizeValidator(limit_value=5242880)]),
        ),
    ]
