# Generated by Django 5.0.4 on 2024-04-21 12:05

import ArticoApp.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_articouser_groups_articouser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='articouser',
            managers=[
                ('objects', ArticoApp.accounts.models.ArticoUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='articouser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
