# Generated by Django 5.0.4 on 2024-04-21 18:08

import ArticoApp.products.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_articouser_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_photo', models.ImageField(upload_to='profile_photo/', validators=[ArticoApp.products.models.MaxFileSizeValidator(limit_value=3145728)])),
                ('profile_banner', models.ImageField(upload_to='profile_banner_photo/', validators=[ArticoApp.products.models.MaxFileSizeValidator(limit_value=3145728)])),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
