# Generated by Django 5.0.4 on 2024-04-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articouser',
            name='slug',
        ),
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=100, unique=True),
        ),
    ]
