# Generated by Django 5.0.4 on 2024-04-21 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_articouser_slug_profile_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='slug',
        ),
        migrations.AddField(
            model_name='articouser',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
